image: docker:20.10.16

services:
  - docker:20.10.16-dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

stages:
  - test
  - build
  - deploy

before_script:
  - docker info

test:
  stage: test
  script:
    - docker-compose config
  only:
    - main
    - merge_requests

build:
  stage: build
  script:
    - docker-compose build
  only:
    - main
    - merge_requests

deploy:
  stage: deploy
  script:
    - echo "Deploy to production server"
  only:
    - main
  when: manual
